public class acc {
    public Integer aa;
    private String ad;
    private string addr='3456fgtgnhn,hghsg';
    public Integer accname
    {
        get{
            return aa;
        }
        set {
            aa= value;
            if (aa<=10)
            {
                aa = 0;
            }
        }
        
    }
    public string getaddress()
    {
        System.debug('Fixed');
        Integer x = 40;
        System.debug(x);
        System.debug('UserStory 4 completed');
        return addr;
            }
            // US 1 build


    }